config/routes.rb
Rails.application.routes.draw do
  get 'privacy/policy'
  get 'home/view'
  resources :iata_codes
  get 'book/flight'
  post 'book/flight'
  root :to => 'home#view' 
   # root :to => 'book#flight'
   # devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/iata_code.rb
class IataCode < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_controller.rb
require "uri"
require "net/http"
require 'json'
require 'pry'
require 'platform-api'

class BookController < ApplicationController
  respond_to :js, :html, :json
  before_action :flight
  # attr_accessor :src, :api
  # validates :should_not_be_equal
  
  # def should_not_be_equal
  #   if :src.present? && dest.present? 
  #     errors.add(:src,"Source & destination can't be same") if :src == :dest
  #   end  
  # end


  def flight
  	
    @codes = []
    IataCode.all.each do |x|
      @codes << [ x.city , x.airport , x.code]
    end
    p1 = params[:start_date]
    
    if p1!=nil
    date1 = p1["year"]
      if p1["month"].to_i < 10
         date1 = date1 + "0" +p1["month"]
      else
        date1 = date1 + p1["month"]
      end
      
      if p1["day"].to_i < 10
         date1 = date1 + "0" +p1["day"]
      else
        date1 = date1 + p1["day"]
      end
    end

    p2 = params[:end_date]
    
    if p2!=nil
    date2 = p2["year"]
      if p2["month"].to_i < 10
         date2 = date2 + "0" +p2["month"]
      else
        date2 = date2 + p2["month"]
      end
      
      if p2["day"].to_i < 10
         date2 = date2 + "0" +p2["day"]
      else
        date2 = date2 + p2["day"]
      end
    end
   
   

    source = params[:src].to_s
    destination = params[:dest].to_s
    dateofdeparture = date1.to_s
    dateofarrival = date2.to_s
    seatingclass = params[:class].to_s
    adults = params[:adults].to_s
    children = params[:child].to_s
    infants = params[:infants].to_s
    counter = params[:counter].to_s 		# 0 - international , 100 - domestic
   if source == destination
    flash[:notice] = "Source and Destination Can't be Same!!!"
   end

   if adults == "" || adults == "0"
     adults ="1"
   end

   if children == ""
     children = "0"
   end

   if infants == ""
    infants = "0"
  end

    @total = adults.to_i + children.to_i + infants.to_i
    @param1 = adults.to_i
    @param2 = children.to_i
    @param3 = infants.to_i
   
    

    begin
    	uri = URI('https://developer.goibibo.com/api/search/')
	   	params = {  "app_id" => "01d613cc" ,
		    			    "app_key" => "2d974c23eaa3034771edbe80db153a34" ,
				          "source" => source ,
					        "destination" => destination, 
	                "dateofdeparture" => dateofdeparture, 
	                "dateofarrival" => dateofarrival ,
	                "seatingclass" => seatingclass,
	                "children" => adults ,
	                "children" => children ,
	                "infants" => infants ,
	                "counter" => "100" }
		uri.query = URI.encode_www_form(params)
    p "completed"
		res = Net::HTTP.get_response(uri)
		# => puts res.body if res.is_a?(Net::HTTPSuccess)
		@result = JSON.parse(res.body) if res.is_a?(Net::HTTPSuccess)
    

    
	    rescue => e
	        puts "failed #{e}"
     end
	
    render "book/flight"
    # respond_to do |format|
    #     format.html { render :controller =>"book", :action => "flight" }
    #     format.json { render  @result }
    #     #format.js
    #   end

  
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def view
  	
  	@codes = []
  	
    IataCode.all.each do |x|
      @codes << [ x.city , x.airport , x.code]
	  end
  end
end

app/controllers/iata_codes_controller.rb
class IataCodesController < ApplicationController
  before_action :set_iata_code, only: [:show, :edit, :update, :destroy]

  # GET /iata_codes
  # GET /iata_codes.json
  def index
    @iata_codes = IataCode.all
  end

  # GET /iata_codes/1
  # GET /iata_codes/1.json
  def show
  end

  # GET /iata_codes/new
  def new
    @iata_code = IataCode.new
  end

  # GET /iata_codes/1/edit
  def edit
  end

  # POST /iata_codes
  # POST /iata_codes.json
  def create
    @iata_code = IataCode.new(iata_code_params)

    respond_to do |format|
      if @iata_code.save
        format.html { redirect_to @iata_code, notice: 'Iata code was successfully created.' }
        format.json { render :show, status: :created, location: @iata_code }
      else
        format.html { render :new }
        format.json { render json: @iata_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /iata_codes/1
  # PATCH/PUT /iata_codes/1.json
  def update
    respond_to do |format|
      if @iata_code.update(iata_code_params)
        format.html { redirect_to @iata_code, notice: 'Iata code was successfully updated.' }
        format.json { render :show, status: :ok, location: @iata_code }
      else
        format.html { render :edit }
        format.json { render json: @iata_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iata_codes/1
  # DELETE /iata_codes/1.json
  def destroy
    @iata_code.destroy
    respond_to do |format|
      format.html { redirect_to iata_codes_url, notice: 'Iata code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iata_code
      @iata_code = IataCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def iata_code_params
      params.require(:iata_code).permit(:city, :airport, :code)
    end
end

app/controllers/privacy_controller.rb
class PrivacyController < ApplicationController
  def policy
  	@codes = []
  	
    IataCode.all.each do |x|
      @codes << [ x.city , x.airport , x.code]
	  end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/iata_codes_helper.rb
module IataCodesHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/views/book/_sechdule.html.erb
<section class="intro">
   <row>
 <% begin %>
<!-- ******************************************LEFT SPLIT ******************************************** -->
  <div class="col-lg-6 col-sm-12 left w3-pale-red">
   <!-- &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& -->

        <div class="container" id="go">
          <div class="w3-container">
          <% begin %>
          <% count1 = 0 %> 
         <% if !@result["data"]["onwardflights"].empty? %>
           
           <strong> <h3 class=" center"> Onward Flights :</h3> </strong>

        <div class="card-deck mb-3 text-center">
           <div class="row"> 
             <% @result["data"]["onwardflights"].each do |x| %>
              <% if x["destination"] == params[:dest].to_s && x["origin"] == params[:src].to_s %>
                 <% count1 += 1 %>
                 <div class="col-sm-4">

                            <div class="card mb-4 box-shadow w3-pale-green">
                                <div class="card-header">
                                  <h4 class="my-0 font-weight-normal"><%= x["airline"] %> </h4>
                                </div>
                                <div class="card-body">
                                  <h1 class="card-title pricing-card-title"> <small>
                        <%= image_tag(x["airline"].downcase.to_s + ".png",alt: "Image Unavailable",  size: "70"   ) %>
                                 </small></h1>
                                  <ul class="list-unstyled mt-3 mb-4">
                                    <li><strong><%= x["origin"] %> --> <%= x["destination"] %></strong></li>
                                    <li>Depature : <%= x["deptime"] %></li>
                                    <li>Duration :<%=  x["duration"] %></li>
                                  </ul>
                                 <!-- Button trigger modal -->
                            
                      <button type="button" class="btn btn-primary btn-block " data-toggle="modal" data-target="#exampleModalCenter<%= count1 %>">
                         Fare</button>
                                </div>

                 
                        </div>   <!-- w3 pale -->

                            <!-- *********************  MODAL **************************** -->
                           

                            <!-- Modal -->
                            <div class="modal fade" id="exampleModalCenter<%= count1 %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                              <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalCenterTitle">Fare</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                  </div>
                                  <div class="modal-body" style="color: black ;">

                                    <b>Base Fare:</b> <%= x["fare"]["adultbasefare"] %> ||
                                    <b>Extra Fares:</b> <%= x["fare"]["grossamount"] - x["fare"]["adultbasefare"] %>
                                    <br>
                                    <strong>Total Fare : <%= x["fare"]["grossamount"] %> </strong>
                                    <br>
                                    <strong>Total Bookings : <%= @total %> </strong>
                                     <ul>
                                     <li>Adult: <%= @param1 %></li>
                                     <li>Children: <%= @param2 %></li>
                                     <li>Infant:<%= @param3 %></li>
                                     </ul>
                                   <div class="w3-pale-green"><h3> Total Fair ( <%= @total %> * <%=x["fare"]["grossamount"] %>  ) : <%= @total * x["fare"]["grossamount"] %> </h3></div>
                                    </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="button" class="btn btn-primary">Confirm</button>
                                  </div>
                                </div>
                              </div>
                            </div>

                            <!-- *********************  MODAL **************************** -->



                </div>    <!-- col sm 4 -->            
                <% end %> 
              <% end %>
          </div>
        </div>
         
          <% end %>
        <% end %> 
         </div>
        </div>



   <!-- &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& -->
  </div>
<!-- ******************************************RIGHT SPLIT ******************************************** -->
  <div class="col-lg-6 col-sm-12 right w3-light-grey">
      <!--    &&&&&&&&&&&&&&&&&&&& -->
               <div class="container" id="go">
              <div class="w3-container">
              <% begin %>
              <% f = "xx" %>
              <% count2= 0 %> 
             <% if !@result["data"]["returnflights"].empty? %>
               
               <strong> <h3 class=" center"> Return Flight :</h3> </strong>

            <div class="card-deck mb-3 text-center">
               <div class="row"> 
                 <% @result["data"]["returnflights"].each do |x| %>
                  <% if x["destination"] == params[:src].to_s && x["origin"] == params[:dest].to_s%>
                     <% count2 += 1 %>
                     <div class="col-sm-4">

                                <div class="card mb-4 box-shadow w3-pale-green">
                                    <div class="card-header">
                                      <h4 class="my-0 font-weight-normal"><%= x["airline"] %> </h4>
                                    </div>
                                    <div class="card-body">
                                      <h1 class="card-title pricing-card-title"> <small>
                           <%= image_tag(x["airline"].downcase.to_s + ".png",alt: "Image Unavailable",  size: "70"   ) %>
                                     </small></h1>
                                      <ul class="list-unstyled mt-3 mb-4">
                                        <li><strong><%= x["origin"] %> --> <%= x["destination"] %></strong></li>
                                        <li>Depature : <%= x["deptime"] %></li>
                                        <li>Duration :<%=  x["duration"] %></li>
                                      </ul>
                                     <!-- Button trigger modal -->
                                
                          <button type="button" class="btn btn-primary btn-block " data-toggle="modal" data-target="#exampleModalCenter<%= f %><%= count2 %>">
                             Fare</button>
                                    </div>

                     
                                </div>   <!-- w3 pale -->

                                <!-- *********************  MODAL **************************** -->
                               

                                <!-- Modal -->
                                <div class="modal fade" id="exampleModalCenter<%= f %><%= count2 %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                  <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalCenterTitle">Fare</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                      </div>
                                      <div class="modal-body">

                                        <b>Base Fare:</b> <%= x["fare"]["adultbasefare"] %> ||
                                        <b>Extra Fares:</b> <%= x["fare"]["grossamount"] - x["fare"]["adultbasefare"] %>
                                        <br>
                                        <strong>Total Fare : <%= x["fare"]["grossamount"] %> </strong>
                                        <br>
                                        <strong>Total Bookings : <%= @total %> </strong>
                                         <ul>
                                         <li>Adult: <%= @param1 %></li>
                                         <li>Children: <%= @param2 %></li>
                                         <li>Infant:<%= @param3 %></li>
                                         </ul>
                                       <div class="w3-pale-green"><h3> Total Fair ( <%= @total %> * <%=x["fare"]["grossamount"] %>  ) : <%= @total * x["fare"]["grossamount"] %> </h3></div>
                                        </div>
                                      <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary">Confirm</button>
                                      </div>
                                    </div>
                                  </div>
                                </div>

                                <!-- *********************  MODAL **************************** -->



                    </div>    <!-- col sm 4 -->            
                    <% end %> 
                  <% end %>
              </div>
            </div>
             
              <% end %>
            <% end %> 
             </div>
      </div>


      <!--  &&&&&&&&&&&&&&&&&&&&&  -->
  
    </div>
<!-- ***********************************************SPLIT END ***************************************************** -->
  <% rescue => e %>
   <% puts "failed #{e}" %>
  <% end %>  
</row>
</section>

app/views/book/flight.js.erb
$("#result").html("<%=escape_javascript(render :partial=>"sechdule")%>");

app/views/iata_codes/_form.html.erb
<%= form_with(model: iata_code, local: true) do |form| %>
  <% if iata_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(iata_code.errors.count, "error") %> prohibited this iata_code from being saved:</h2>

      <ul>
      <% iata_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :airport %>
    <%= form.text_field :airport %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/iata_codes/edit.html.erb
<h1>Editing Iata Code</h1>

<%= render 'form', iata_code: @iata_code %>

<%= link_to 'Show', @iata_code %> |
<%= link_to 'Back', iata_codes_path %>

app/views/iata_codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Iata Codes</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Airport</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @iata_codes.each do |iata_code| %>
      <tr>
        <td><%= iata_code.city %></td>
        <td><%= iata_code.airport %></td>
        <td><%= iata_code.code %></td>
        <td><%= link_to 'Show', iata_code %></td>
        <td><%= link_to 'Edit', edit_iata_code_path(iata_code) %></td>
        <td><%= link_to 'Destroy', iata_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Iata Code', new_iata_code_path %>

app/views/iata_codes/new.html.erb
<h1>New Iata Code</h1>

<%= render 'form', iata_code: @iata_code %>

<%= link_to 'Back', iata_codes_path %>

app/views/iata_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @iata_code.city %>
</p>

<p>
  <strong>Airport:</strong>
  <%= @iata_code.airport %>
</p>

<p>
  <strong>Code:</strong>
  <%= @iata_code.code %>
</p>

<%= link_to 'Edit', edit_iata_code_path(@iata_code) %> |
<%= link_to 'Back', iata_codes_path %>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <title>Bookflight</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

   <style>
   body{
    background-color:rgba(0,0,255,0.3);
   }
      
  </style>
  <script>
   // function validateForm() {
  //   console.log("javascript wotking");
  //   // var x = document.getElementsByClassName('terminal1');
  //   var x = document.querySelector(".terminal1")[0].value ;
  //   var y = document.querySelector(".terminal2")[0].value ;
  //   console.log(x);
  //   console.log(y);
  //   if (x == y) {
  //       alert("Source and Destination Can't be Same!!!");
  //       return false;
  //     }
  // }
  </script>  

  </head>

  
  <body>
     
 
 <section class="banner" id="top">
  
<!-- *********************************************Nav Bar******************************************************** -->
    
        <nav class="navbar navbar-inverse">
          <div class="container-fluid">
            <div class="navbar-header active">
            </div>
            <ul class="nav navbar-nav">

              <li > <%= link_to "Home" , home_view_path %>  </li>
              <li><%= link_to  "Policy" , privacy_policy_path %></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <div style="padding-top: 7px; padding-right: 8px;">
         <% unless current_user %> 
              
              <%= link_to "Sign Up", user_facebook_omniauth_authorize_path , class: "btn btn-success" %>
              <% else %>
              <% current_user[:name] %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete , class: "btn btn-danger" %>
           
            <% end %>      
              </div>
             </ul>
          </div>
        </nav>



<!-- ******************************************************************************************************** -->
      <div class="container">
         <% if flash[:notice] %>
       <strong><h3 style="color: white;">   <div class="notice"><%= flash[:notice] %></div> </h3></strong>
        <% end %>
        <div class="row">
                      <div class="col-md-5">
                          <div class="left-side">
                              <div class="logo">
                                  <img src= " <%= asset_path "logo.png" %>" alt="Flight Template">
                              </div>
                              <div class="w3-container">
                              <% if user_signed_in? %>
                              <strong><h4 style="color: white;">Welcome , <%= current_user.name %></h4></strong>
                              <img src= "<%= current_user.image %>" alt="Img not found"  class="w3-circle center">
                              <% end %>
                              </div>
                              <div class="tabs-content">
                                  <h4>Choose Your Direction:</h4>
                                  <ul class="social-links">
                                      <li><a href="https://www.facebook.com/PankajSharma1181998">Find me on <em>Facebook</em><i class="fa fa-facebook"></i></a></li>
                                      <li><a href="https://www.linkedin.com/in/pankaj-s-096865b5/ ">Connect on <em>LinkedIn</em> <i class="fa fa-youtube"></i></a></li>
                                      <li><a href="https://github.com/pankaj1181998">Check Out <em>Github</em><i class="fa fa-instagram"></i></a></li>
                                  </ul>
                              </div>
                              
                          </div>
                      </div>


<!-- ******************************************************************************************************** -->

 <!--   
  <div class="spinner" id="spinner">  
    <div class="sk-folding-cube">
          <div class="sk-cube1 sk-cube"></div>
          <div class="sk-cube2 sk-cube"></div>
          <div class="sk-cube4 sk-cube"></div>
          <div class="sk-cube3 sk-cube"></div>
    </div>
 </div> -->

 

 <%= form_tag("/book/flight", method: "post " , html: {id: "id_form_location"}) do %> 
  
  <div class="col-md-5 col-md-offset-1">
              
                    <section id="first-tab-group" class="tabgroup">
                        <div id="tab1">
                            <div class="submit-form">
                                <h4>Check availability for <em>direction</em>:</h4>
                                    <div class="row">
                                      <div class="col-md-6">
                                          <fieldset>
                                              <label for="from">From:</label>
                                             <%= select_tag(:src, options_for_select(@codes), :class => "terminal1") %> 
                                          </fieldset>
                                      </div>
                                      

                                    <div class="col-md-6">
                                        <fieldset>
                                            <label for="to">To:</label>
                                            <%= select_tag(:dest, options_for_select(@codes), :class => "terminal2") %>
                                        </fieldset>
                                    </div>

                                    <div class="col-md-6">
                                        <fieldset>
                                            <label for="departure">Departure date:</label>
                                        <%= select_date Date.today, prefix: :start_date ,:class => "form-control" %>
                                            
                                        </fieldset>
                                     </div>
                                   
                                   <div class="col-md-6">
                                        <fieldset>
                                            <label for="departure">Return date:</label>
                                        <%= select_date Date.today, prefix: :end_date ,:class => "form-control" %>
                                            
                                        </fieldset>
                                     </div>

                                    <div class="col-md-6">
                                        <fieldset>
                                            <label for="return">Adults(1-9):</label>
                                  <%= text_field_tag :adults , "", placeholder: "1" , class: "form-control" , id: "return" ,required: true %>
                                        </fieldset>
                                    </div> ,

                                    <div class="col-md-6">
                                        <fieldset>
                                            <label for="return">Children(0-9):</label>
                                 <%= text_field_tag :child , "" , placeholder: "0" ,class: "form-control" , id: "return", required: true %>
                                        </fieldset>
                                    </div>

                                    <div class="col-md-6">
                                        <fieldset>
                                            <label for="return">Infants:</label>
                                      <%= text_field_tag :infants , "" , placeholder: "0" , class: "form-control" , id: "return", required: true  %>
                                        </fieldset>
                                    </div>

                                      <div class="col-md-6">
                                         <label for="to">Class:</label>
                                   <%= select_tag(:class, options_for_select([["Economy", "E"], ["Business", "B"]] ) ) %>
                                      </div>


                                      <div class="col-md-6">
                                          <fieldset>
   <%= button_to "Order Ticket Now", book_flight_path, { :onclick => "validateForm()", :class=>"btn btn-success submit" }  %>
   <!-- <button type="submit" id="form-submit button-upload" class="btn btn-success submit" >
   Order Ticket Now</button> -->
                                          </fieldset>
                                      </div>

                                  </div>
                                  
                              </div>
                          </div>
                      </section>
                  </div>
 <% end %>


<!-- ********************************************************************************************************** -->
          </div>
        </div>
    </section>

   <%= yield %>

  </body>
</html>